development:
  adapter: postgresql
  encoding: unicode
  database: skiller_dev
  pool: 5
  username: skiller
  password: skiller

test:
  development:
    adapter: postgresql
    encoding: unicode
    database: skiller_test
    pool: 5
    username: skiller
    password: skiller

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5